#! /usr/bin/env bash


usage() {
cat <<EOF

[Usage] revcomp [mode] textfile > outfile

By default, outputs the reverse-complement. Use the first argument to specify a different mode of operation:
[r] or [reverse] for reverse only
[c] or [complement] for complement only

[Example] revcomp oligos.txt > revcomp_oligos.txt
[Example] revcomp reverse oligots.txt > reverse_oligos.txt

EOF
}

if [[ -z "$1" ]]; then
    echo -e "\n  Returns the reverse-complement of DNA bases in a text file."
    usage
    exit
fi

if [[ -z "$2" ]]; then
    while IFS= read -r line
    do
        echo "$line" | tr 'ATCG' 'TAGC' | rev
    done < "$1"
else   
    case "$1" in
        reverse | r )
            while IFS= read -r line
            do
                echo "$line" | rev
            done < "$2"
        ;;
        complement | c )
            while IFS= read -r line
            do
                echo "$line" | tr 'ATCG' 'TAGC'
            done < "$2"
        ;;
    *)
        echo "Invalid mode of operation: $1"
        usage
        ;;
    esac

fi
