#! /usr/bin/env julia

if ARGS[1] == "revcomp"
    using BioSequences
    x=ARGS[2]
    function revcomp(x)
        sequences= open(readlines,x)
        outfile=open("reverse_complement_seqs.txt","w")
        for i in sequences
            write(outfile,join(reverse_complement(DNASequence(i))),"\n")
        end
        print("Your sequences are located in the file reverse_complement_seqs.txt")
    end ;
    revcomp(x)
elseif ARGS[1] == "comp"
    using BioSequences
    x=ARGS[2]
    function revcomp(x)
        sequences= open(readlines,x)
        outfile=open("complement_seqs.txt","w")
        for i in sequences
            write(outfile,join(reverse_complement(DNASequence(i))),"\n")
        end
        print("Your sequences are located in the file complement_seqs.txt")
    end ;
    revcomp(x)
elseif ARGS[1] == "rev"
    using BioSequences
    x=ARGS[2]
    function revcomp(x)
        sequences= open(readlines,x)
        outfile=open("reverse_seqs.txt","w")
        for i in sequences
            write(outfile,join(reverse(DNASequence(i))),"\n")
        end
        print("Your sequences are located in the file reverse_seqs.txt")
    end ;
    revcomp(x)
else
    print("This julia script takes a simple file of one-per-line sequences and outputs \na file of the reverse complements of those sequences \n \n[usage] reversecomp.jl <mode> <indexfile> \nmodes: rev | comp | revcomp ")
end
