#! /usr/bin/env julia
if length(ARGS)==0
    print("This julia script takes a simple file of one-per-line sequences and outputs \na file of the reverse complements of those sequences \n \n[usage] reversecomp <mode> <indexfile> \nmodes: rev | comp | revcomp ")
elseif occursin(ARGS[1], "comp rev revcomp")
    using BioSequences
    outfilename = ARGS[1]*"_seqs.txt"
    function revcomp()
        sequences = open(readlines,ARGS[2]);
        outfile=open(outfilename,"w");
        for i in sequences
            if ARGS[1] == "revcomp"
                write(outfile,join(reverse_complement(DNASequence(i))),"\n")
            elseif ARGS[1] == "comp"
                write(outfile,join(complement(DNASequence(i))),"\n")
            else write(outfile,join(reverse(DNASequence(i))),"\n")
            end
        end
        close(outfile)
    end ;
    revcomp()
    print("Your sequences are located in the file ", outfilename)
else
    print("error: incorrect usage \n \n[usage] reversecomp <mode> <indexfile>\n")
    print("[example] reversecomp rev crabseqs.txt")
    print("\nmodes: rev | comp | revcomp ")
end
