#! /usr/bin/env bash

#====== USAGE ======#

sam2bam filename.sam

#===================#

FILENAME=`echo "$1" | cut -d '.' -f1`

# convert SAM to BAM
samtools view -hb $1 > $FILENAME.bam

# sort the BAM
samtools view -h -F4 $FILENAME.bam | samtools sort -m 16G -l0 > $FILENAME.sorted.bam

# index sorted BAM
samtools index $FILENAME.sorted.bam
