#! /usr/bin/env bash

if [[ -z "$1" ]]; then
    echo -e "\n  This script will convert a SAM file into a BAM file. It will also sort and index the file, along with removing unmapped reads. Provide the number of threads as the second argument to run everything multithreaded."
    echo -e "\n [usage] sam2bam filename.sam threads"
    exit
fi

if [[ -z "$2" ]]; then
    THREADS=1
else
    THREADS=$2
fi

FILENAME=`echo "$1" | cut -d '.' -f1`

# convert SAM to BAM & remove unmapped | sort the bam
samtools view -hb -F4 $1 -@$THREADS | samtools sort -m 16G -l0  -@$THREADS > $FILENAME.bam

## deprecated ##
# remove unmapped | sort the BAM
#samtools view -h -F4 $FILENAME.bam -@$THREADS | samtools sort -m 16G -l0  -@$THREADS > $FILENAME.sorted.bam
##

# index sorted BAM
samtools index $FILENAME.bam -@$THREADS
