#! /usr/bin/env Rscript

args = commandArgs(trailingOnly = TRUE)

if (length(args)==0) {
  system("echo Filter individuals with excess or deficient heterozygosity")
  system("echo \"Detects heterozygosity outliers using the Tukey Q1 + (1.5x IQR) method\"")
  system("echo -e \"\n>> must be run in the same directory as the input VCF file <<\"")
  system("echo -e \"\n[usage]:   vcf_hwe_individual_filter <vcf_file>\"")
  system("echo -e \"\n[requires]: VCFtools and R\"")     
  q()
}

# Silently load dplyr library, or install it if necessary
suppressMessages(if (!require("dplyr")) install.packages("dplyr"))
suppressMessages(library("dplyr"))

setwd(getwd())

## use VCFtools to perform heterozygosity calculations
het_calc <- paste("vcftools --vcf ", args[1], " --out individuals --het")
system(het_calc)

## Import into R and perform outlier analysis
individuals <- read.delim("~/individuals.het")

## calculate Inter-Quartile Range (Q3-Q1) 
iqr <- IQR(individuals$F)

# calculate low threshold Q1 - (1.5 x IQR)
low <- as.numeric(quantile(individuals$F, 0.25)) - (1.5 * iqr)

# calculate high threshold Q3 + (1.5 x IQR)
high <- as.numeric(quantile(individuals$F, 0.75)) + (1.5 * iqr)

## Simple plots if you want them
#hist(individuals$F, breaks = 50, main = "Heterozygosity F scores")
#abline(v = low)
#abline(v = high)

# Isolate individuals with F scores either above or below high/low thresholds, respectively

filtered_tukey <- filter(individuals, F < low | F > high)

# get low/high counts for printing output
num_low <- filter(individuals, F < low)$INDV %>% length
num_high <- filter(individuals, F > high)$INDV %>% length

# print number of indidivuals flagged to terminal
print_num <- paste("echo \"  - Number of individuals flagged for removal: ", 
                  length(filtered_tukey$INDV), 
                  " (", 
                  num_low,
                  " below + ",
                  num_high,
                  " above threshold)\"",
                  sep = ""
)
system(print_num)

# write individuals flagged for removal to file
system("echo \"  - Writing flagged individuals to file het_outliers_to_rm.txt\"")
write.table(filtered_tukey[1], 
            file = "het_outliers_to_rm.txt", 
            col.names= FALSE, 
            row.names = FALSE, 
            quote = FALSE
)


# Perform individual removal
rm_ind_text <- paste("echo \"  - Removing flagged individuals from ", args[1], "using VCFtools\"")
system(rm_ind_text)

rm_ind <- paste("vcftools --vcf", args[1], "--recode --recode-INFO-all --out Het_indiv_filtered --remove het_outliers_to_rm.txt")
system(rm_ind)

system("echo -e \"\nIndividual heterozygosity filtering is complete.\nYour filtered file is named: Het_indiv_filtered.recode.vcf\"")
