#! /usr/bin/env bash

info() {
cat <<EOF

Converts PacBio bam files into fasta or fastq format using bam2fastx
provided by PacBio https://github.com/PacificBiosciences/bam2fastx

[usage]:	unpaq fastq/a -o <outfile.name> -d <working.directory>
[example]: unpaq fasta -o pangolin_1  ./pangolin_pbio

-o <prefix>       | output filename
-d <directory>    | path to working directory

EOF
}

usage() {
cat <<EOF

[usage]:	unpaq fastq/a -o <outfile.name> -d <working.directory> -q <optional>
[example]: unpaq fasta -o armadillo  ./

EOF
}

if [[ -z "$1" ]]; then
  info
  exit 1
fi

while getopts ":p:d:" opt; do
  case $opt in
    p)
      echo "output file will be named $OPTARG.f*.gz" 
      PREFIX=$OPTARG
      ;;
    d)
      WORKDIR=$OPTARG
      echo "working directory set to: $(readlink -f $OPTARG)"
      ;;
    \?)
      echo "Invalid option: -$OPTARG" 
      usage
      exit 1
      ;;
    :)
      echo "-$OPTARG requires an argument." 
      usage
      exit 1
      ;;
  esac
done

if [ "$1" == 'fastq' ] ; then
    echo "Do you want to process scraps.bam files too? This will take a lot longer. (y/n)"
    read $SCRAPS
    bam2fastq -o $PREFIX $(find $WORKDIR -name "*.subreads.bam")
    if [ "$SCRAPS" == 'y' ] ; then
        bam2fastq -o $PREFIX $(find $WORKDIR -name "*.scraps.bam")
    fi
else ;
    bam2fasta -o $PREFIX $(find $WORKDIR -name "*.scraps.bam")
    echo "Do you want to process scraps.bam files too? This will take a lot longer. (y/n)"
    read $SCRAPS
    if [ "$SCRAPS" == 'y' ] ; then
        bam2fasta -o $PREFIX $(find $WORKDIR -name "*.scraps.bam")
    fi
fi

exit 1
