#! /usr/bin/env bash

usage() {
cat <<EOF

Usage: $0 -r <output.prefix> -s

This script will convert PacBio bam files into fasta format using samtools,
then it concatenates them into a single file and counts the number of base
pairs and total number of contigs in the concatenated file.
Optional: Use -s to also process scraps files.
        [example]
$0 -o MAHI -s

EOF
        }

process_subreads() {

  mkdir subreads_fasta
  echo "...converting subreads.bam files to fasta..."
  find ./*/* -name '*.subreads.bam' | parallel "samtools fasta {} > ./subreads_fasta/{/}.subreads.fasta"
  echo "...concatenating fasta files..."
  cat ./subreads_fasta/*subreads.fasta > ./subreads_fasta/$PREFIX.all.subreads.fasta
  echo "...counting the number of contigs in the subreads..."
  echo "Total contigs present in subreads: $(grep -c ">" ./subreads_fasta/$PREFIX.all.subreads.fasta)" >> ./subreads_fasta/$PREFIX.pacbio_subreads_stats.txt
  echo "...counting the number of base pairs in the subreads..."
  echo "Total basepairs present in the subreads: $(grep -v ">" ./subreads_fasta/$PREFIX.all.subreads.fasta | wc | awk '{print $3-$1}')" >> ./subreads_fasta/$PREFIX.pacbio_subreads_stats.txt
  rename .subreads.bam.subreads.fasta .subreads.fasta ./subreads_fasta/*.subreads.bam.subreads.fasta
  head ./subreads_fasta/$PREFIX.pacbio_subreads_stats.txt
}

process_scraps() {
  mkdir scraps_fasta
  echo "...converting scraps.bam files to fasta..."
  find ./*/* -name '*.scraps.bam' | parallel "samtools fasta {} > ./scraps_fasta/{/}.scraps.fasta"
  echo "...concatenating fasta files..."
  cat ./scraps_fasta/*scraps.fasta > ./scraps_fasta/$PREFIX.all.scraps.fasta
  echo "...counting the number of contigs in the scraps..."
  echo "Total contigs present in scraps: $(grep -c ">" ./scraps_fasta/$PREFIX.all.scraps.fasta)" >> ./scraps_fasta/$PREFIX.pacbio_scraps_stats.txt
  echo "...counting the number of base pairs in the scraps..."
  echo "Total basepairs present in the scraps: $(grep -v ">" ./scraps_fasta/$PREFIX.all.scraps.fasta | wc | awk '{print $3-$1}')" >> ./scraps_fasta/$PREFIX.pacbio_scraps_stats.txt
  rename .scraps.bam.scraps.fasta .scraps.fasta ./scraps_fasta/*.scraps.bam.scraps.fasta
  head ./scraps_fasta/$PREFIX.pacbio_scraps_stats.txt
}

# code chunk for usage when no argument given
if [[ -z "$1" ]]; then
  usage
  exit 1
fi
#

PREFIX=

while getopts ":o:s" opt; do
  case $opt in
    o)
      echo "fasta file prefix set to: $OPTARG" >&2
      PREFIX=$OPTARG
      process_subreads
  		;;
    s)
      process_scraps
      exit 1
      ;;
	\?)
      echo "Invalid option: -$OPTARG" >&2
      usage
      exit 1
      ;;
  :)
      echo "-$OPTARG requires a prefix to name the concatenated fasta file." >&2
      usage
      exit 1
      ;;
  esac
done

exit 1
